services:
  ollama:
    image: sh-harbor.mthreads.com/haive/ollama:${OLLAMA_DOCKER_TAG-latest}
    pull_policy: always
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    # libmusa/libmusart requires SYS_NICE on calling set_mempolicy
    cap_add:
      - SYS_NICE
    tty: true
    restart: unless-stopped


  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    pull_policy: always
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped


volumes:
  ollama: {}
  open-webui: {}